<a href="https://colab.research.google.com/github/divya200212/DL-RL-CS-704/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Create an array with zeros
zeros_array = np.zeros((3, 3))
print("Zeros Array:\n", zeros_array)
# Create an array with ones
ones_array = np.ones((2, 2))
print("Ones Array:\n", ones_array)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Addition
sum_array = np.add(a, b)
print("Sum:", sum_array)
# Subtraction
diff_array = np.subtract(a, b)
print("Difference:", diff_array)
# Multiplication
product_array = np.multiply(a, b)
print("Product:", product_array)
# Division
quotient_array = np.divide(a, b)
print("Quotient:", quotient_array)

Sum: [5 7 9]
Difference: [-3 -3 -3]
Product: [ 4 10 18]
Quotient: [0.25 0.4  0.5 ]


In [ ]:
import numpy as np
# Create two matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
# Matrix multiplication
matrix_product = np.dot(matrix_a, matrix_b)
print("Matrix Product:\n", matrix_product)

Matrix Product:
 [[19 22]
 [43 50]]


In [ ]:
import numpy as np
# Create an array and a scalar
array = np.array([1, 2, 3])
scalar = 2
# Broadcasting
broadcasted_array = array * scalar
print("Broadcasted Array:", broadcasted_array)

Broadcasted Array: [2 4 6]


In [ ]:
import numpy as np
# Create an array
data = np.array([1, 2, 3, 4, 5])
# Mean
mean_value = np.mean(data)
print("Mean:", mean_value)
# Standard deviation
std_value = np.std(data)
print("Standard Deviation:", std_value)
# Sum
sum_value = np.sum(data)
print("Sum:", sum_value)

Mean: 3.0
Standard Deviation: 1.4142135623730951
Sum: 15


In [ ]:
import numpy as np
# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6])
# Reshape to 2x3
reshaped_array = array.reshape((2, 3))
print("Reshaped Array:\n", reshaped_array)
# Reshape to 3x2
reshaped_array = array.reshape((3, 2))
print("Reshaped Array:\n", reshaped_array)



Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
# Create two arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
# Element-wise addition
add_result = array_a + array_b
print("Element-wise Addition:", add_result)
# Element-wise multiplication

multiply_result = array_a * array_b
print("Element-wise Multiplication:", multiply_result)

Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]


In [ ]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing an element
element = array_2d[1, 1]
print("Element at [1, 1]:", element)
# Accessing a row
row = array_2d[1, :]
print("Row 1:", row)
# Accessing a column
column = array_2d[:, 1]
print("Column 1:", column)

Element at [1, 1]: 5
Row 1: [4 5 6]
Column 1: [2 5 8]


In [ ]:
import numpy as np

# Create a random array
random_array = np.random.rand(3, 3)
print("Random Array:\n", random_array)
# Create a random integer array
random_int_array = np.random.randint(0, 10, (3, 3))
print("Random Integer Array:\n", random_int_array)

Random Array:
 [[0.2558224  0.32382034 0.69038153]
 [0.65117444 0.91049689 0.51986612]
 [0.4156565  0.53786523 0.62222628]]
Random Integer Array:
 [[6 0 3]
 [3 6 7]
 [7 7 9]]


In [ ]:
import numpy as np
# Create two arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
# Vertical stack
v_stack = np.vstack((array_a, array_b))
print("Vertical Stack:\n", v_stack)
# Horizontal stack
h_stack = np.hstack((array_a, array_b))
print("Horizontal Stack:", h_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]


In [ ]:
import numpy as np

# Generate 10 equally spaced numbers between 0 and 1
arr = np.linspace(0, 1, 10)

print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
import numpy as np

# Generate 20 random integers between 1 and 100
arr = np.random.randint(1, 101, 20)

print(arr)


[43  8 62 12 77 10 33 20 13 29 40 43 86 61 67 36  2 73 16 15]


In [ ]:
import numpy as np

# Create a 2D array with shape (4, 4) filled with the value 7
arr = np.full((4, 4), 7)

print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
import numpy as np

# Create a 1D array of 10 elements with the value 3.14
arr = np.full(10, 3.14)

print(arr)


[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [ ]:
import numpy as np

# Create a 2D array with shape (3, 3) and values ranging from 1 to 9
arr = np.arange(1, 10).reshape(3, 3)

print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

# Perform element-wise subtraction
result = a - b

print(result)


[-1 -1 -1 -1 -1]


In [ ]:
import numpy as np

# Define array a
a = np.array([2, 4, 6, 8])

# Multiply array a by 3
a = a * 3

print(a)


[ 6 12 18 24]


In [ ]:
import numpy as np

# Define array a
a = np.array([10, 20, 30, 40])

# Divide array a by 2
a = a / 2

print(a)



[ 5. 10. 15. 20.]


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([5, 10, 15])
b = np.array([2, 3, 4])

# Perform element-wise modulus
result = np.mod(a, b)

print(result)

[1 1 3]


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(a, b)

print(dot_product)

32


In [ ]:
import numpy as np

# Define matrices a and b
a = np.array([[2, 3],
              [4, 5]])

b = np.array([[1, 0],
              [0, 1]])

# Perform matrix multiplication
result = np.matmul(a, b)  # or equivalently: a @ b

print(result)

[[2 3]
 [4 5]]


In [ ]:
import numpy as np

# Define a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define a 3x1 vector (as a 1D array in NumPy)
v = np.array([1, 2, 3])

# Perform matrix multiplication (A * v)
result = np.matmul(A, v)  # or equivalently: A @ v

print(result)

[14 32 50]


In [ ]:
import numpy as np

# Generate a 4x4 identity matrix
identity_matrix = np.identity(4)

# Generate a 4x4 matrix filled with random integers (between 0 and 9 for example)
random_matrix = np.random.randint(0, 10, (4, 4))

# Perform matrix multiplication
result = np.matmul(identity_matrix, random_matrix)

# Print the results
print("Identity Matrix:")
print(identity_matrix)
print("\nRandom Matrix:")
print(random_matrix)
print("\nResult of Matrix Multiplication (Identity Matrix * Random Matrix):")
print(result)


Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Matrix:
[[0 8 2 4]
 [7 6 1 0]
 [9 8 6 4]
 [7 2 0 1]]

Result of Matrix Multiplication (Identity Matrix * Random Matrix):
[[0. 8. 2. 4.]
 [7. 6. 1. 0.]
 [9. 8. 6. 4.]
 [7. 2. 0. 1.]]


In [ ]:
import numpy as np

# Define matrices a and b
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Perform matrix multiplication
result = np.matmul(a, b)  # or equivalently: a @ b

print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
import numpy as np

# Define a 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define a 3x2 matrix
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Perform matrix multiplication
result = np.matmul(A, B)  # or equivalently: A @ B

print(result)


[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np

# Create a 1D array
array = np.array([10, 20, 30])

# Subtract a scalar value using broadcasting
result = array - 5

print(result)


[ 5 15 25]


In [ ]:
import numpy as np

# Create a 3x3 array
array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Create a 3x1 array (as a column vector)
array_3x1 = np.array([[10],
                      [20],
                      [30]])

# Add them using broadcasting
result = array_3x3 + array_3x1

print(result)


[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [ ]:
import numpy as np

# Create a 4x4 array
array_4x4 = np.array([[10, 20, 30, 40],
                      [50, 60, 70, 80],
                      [90, 100, 110, 120],
                      [130, 140, 150, 160]])

# Divide by a scalar value using broadcasting
result = array_4x4 / 2

print(result)


[[ 5. 10. 15. 20.]
 [25. 30. 35. 40.]
 [45. 50. 55. 60.]
 [65. 70. 75. 80.]]


In [ ]:
import numpy as np

# Create a 3x3 array
array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Add 3 to each element using broadcasting
result = array_3x3 + 3

print(result)


[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

# Create a 1D array of shape (5,)
array_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array of shape (5, 5)
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25]])

# Multiply using broadcasting
result = array_1d[:, np.newaxis] * array_2d  # or equivalently: array_1d.reshape(-1, 1) * array_2d

print(result)

[[  1   2   3   4   5]
 [ 12  14  16  18  20]
 [ 33  36  39  42  45]
 [ 64  68  72  76  80]
 [105 110 115 120 125]]


In [ ]:
import numpy as np

# Define the array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the median
median = np.median(data)

print("Median of the array:", median)

Median of the array: 5.5


In [ ]:
from statistics import mode

# Define the array
data = [1, 2, 2, 3, 4, 4, 4, 5, 6]

# Calculate the mode
mode_value = mode(data)

print("Mode of the array:", mode_value)

Mode of the array: 4


In [ ]:
import numpy as np

# Define the array
data = np.array([10, 20, 30, 40, 50])

# Calculate the range
data_range = np.max(data) - np.min(data)

print("Range of the array:", data_range)


Range of the array: 40


In [ ]:
import numpy as np

# Define the array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the 25th percentile
percentile_25 = np.percentile(data, 25)

print("25th percentile of the array:", percentile_25)


25th percentile of the array: 3.25


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 10])

# Calculate the correlation coefficient
correlation_coefficient = np.corrcoef(a, b)[0, 1]

print("Correlation coefficient between a and b:", correlation_coefficient)

Correlation coefficient between a and b: 0.9999999999999999


In [ ]:
import numpy as np

# Create a 1D array of 12 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the array to a 3x4 array
array_3x4 = array_1d.reshape(3, 4)

print("Original 1D array:")
print(array_1d)
print("\nReshaped 3x4 array:")
print(array_3x4)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

# Create a 2D array of shape (6, 2)
array_2d = np.array([[1, 2],
                     [3, 4],
                     [5, 6],
                     [7, 8],
                     [9, 10],
                     [11, 12]])

# Reshape the array to shape (3, 4)
array_3x4 = array_2d.reshape(3, 4)

print("Original 2D array (shape 6x2):")
print(array_2d)
print("\nReshaped 2D array (shape 3x4):")
print(array_3x4)

Original 2D array (shape 6x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped 2D array (shape 3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

# Create a 4x4 array
array_4x4 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

# Flatten the array into a 1D array
array_flat = array_4x4.flatten()

print("Original 4x4 array:")
print(array_4x4)
print("\nFlattened 1D array:")
print(array_flat)

Original 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Flattened 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
import numpy as np

# Create a 3D array of shape (2, 3, 4)
array_3d = np.array([[[ 1,  2,  3,  4],
                      [ 5,  6,  7,  8],
                      [ 9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# Reshape the array to shape (4, 3, 2)
array_4x3x2 = array_3d.reshape(4, 3, 2)

print("Original 3D array (shape 2x3x4):")
print(array_3d)
print("\nReshaped 3D array (shape 4x3x2):")
print(array_4x3x2)

Original 3D array (shape 2x3x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Reshaped 3D array (shape 4x3x2):
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [ ]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape to a 2D array with 1 row and as many columns as needed
array_2d = array_1d.reshape(1, -1)

print("Original 1D array:")
print(array_1d)
print("\nReshaped 2D array (1 row, many columns):")
print(array_2d)

Original 1D array:
[1 2 3 4 5 6 7 8]

Reshaped 2D array (1 row, many columns):
[[1 2 3 4 5 6 7 8]]


In [ ]:
import numpy as np

# Create arrays a and b
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

# Perform element-wise division
result = a / b

print("Result of element-wise division:")
print(result)


Result of element-wise division:
[0.5        0.75       0.83333333]


In [ ]:
import numpy as np

# Create arrays a and b
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

# Perform element-wise modulus
result = np.mod(a, b)

print("Result of element-wise modulus:")
print(result)


Result of element-wise modulus:
[0 1 1]


In [ ]:
import numpy as np

# Create array a
a = np.array([1, 2, 3, 4, 5])

# Add 10 to each element
result = a + 10

print("Result after adding 10 to each element:")
print(result)

Result after adding 10 to each element:
[11 12 13 14 15]


In [ ]:
import numpy as np

# Create array a
a = np.array([1, 2, 3, 4, 5])

# Add 10 to each element
result = a + 10

print("Result after adding 10 to each element:")
print(result)

Result after adding 10 to each element:
[11 12 13 14 15]


In [ ]:
import numpy as np

# Create array b
b = np.array([10, 20, 30, 40, 50])

# Subtract 5 from each element
result = b - 5

print("Result after subtracting 5 from each element:")
print(result)

Result after subtracting 5 from each element:
[ 5 15 25 35 45]


In [ ]:
import numpy as np

# Create array c
c = np.array([1, 2, 3, 4, 5])

# Square each element
result = np.square(c)

print("Result after squaring each element:")
print(result)

Result after squaring each element:
[ 1  4  9 16 25]


In [ ]:
# Define the 3D array
array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

# Access the element at index [1, 1, 1]
element = array_3d[1][1][1]

print("Element at index [1, 1, 1]:", element)


Element at index [1, 1, 1]: 11


In [ ]:
# Define the 3D array
array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

# Slice the first layer (first dimension)
first_layer = array_3d[0]

print("First layer (first dimension) of the 3D array:")
print(first_layer)

First layer (first dimension) of the 3D array:
[[1, 2, 3], [4, 5, 6]]


In [ ]:
# Define the 2D array
array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

# Access the last row using negative indexing
last_row = array_2d[-1]

print("Last row of the 2D array:")
print(last_row)

Last row of the 2D array:
[70, 80, 90]


In [ ]:
array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

# Initialize an empty list to store the elements from the first column
first_column_elements = []

# Iterate through each sublist (row) in the 2D array
for sublist in array_2d:
    # Append the element at the first index (index 0) of each sublist to the list
    first_column_elements.append(sublist[0])

# Print the elements of the first column
print("Elements in the first column:")
for element in first_column_elements:
    print(element)


Elements in the first column:
10
40
70


In [ ]:
array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

# Slice the last two rows
last_two_rows = array_2d[1:]  # This selects rows starting from index 1 to the end

# Slice the last two columns from each row in the sliced array
last_two_columns = [row[:-2] for row in last_two_rows]  # This selects elements up to the second-to-last element in each row

print(last_two_columns)

[[40], [70]]


In [ ]:
import random

# Generate a random array of 20 elements with values between 0 and 1
random_array = [random.random() for _ in range(20)]

print(random_array)

[0.9921742994199596, 0.6699560456830779, 0.9623977640004338, 0.23723775508028344, 0.5280575336103731, 0.9866718995616152, 0.6236881633225926, 0.36592225288547287, 0.2780825874181241, 0.5731469329256972, 0.7252969396597538, 0.9777676683505911, 0.5136767084263326, 0.8043494616201703, 0.31864132777165965, 0.5645274198711102, 0.43619665342223124, 0.6224207301683075, 0.21496162755548942, 0.21588281593387482]


In [ ]:
import numpy as np

# Generate a 4x4 array with random integers between 10 and 20
array = np.random.randint(10, 21, size=(4, 4))

print(array)


[[14 17 13 20]
 [12 13 10 10]
 [18 15 15 12]
 [20 12 17 15]]


In [ ]:
import numpy as np

# Generate a 3x3 array with random floats between -1 and 1
array = np.random.uniform(-1, 1, size=(3, 3))

print(array)

[[-0.62932161 -0.22503244 -0.47724371]
 [ 0.55602241 -0.01038123  0.5778835 ]
 [-0.36290594  0.04954198  0.85356289]]


In [ ]:
import numpy as np

# Generate an array of 15 random integers between 100 and 200
array = np.random.randint(100, 201, size=15)

print(array)

[194 166 107 183 138 200 170 137 117 168 101 103 123 195 165]


In [ ]:
import numpy as np

# Generate a 5x5 array with random floats between 0 and 10
array = np.random.uniform(0, 10, size=(5, 5))

print(array)

[[8.73989549 9.98168868 6.6190388  6.39556593 1.43612529]
 [0.86518886 9.42116942 4.47258851 9.1612094  0.20402643]
 [5.10100418 0.33523216 8.58355501 9.9049259  2.56919385]
 [4.91788652 0.22513901 8.55784249 8.85973415 8.33734562]
 [6.95381472 9.3769039  0.14755074 9.87230402 5.2745703 ]]


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertically stack arrays a and b
result = np.vstack((a, b))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Horizontally stack arrays a and b
result = np.hstack((a, b))

print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

# Define arrays a and b as 1D NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate arrays a and b
result = np.concatenate((a, b))

print(result)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

# Concatenate arrays a and b along rows (vertically)
result = np.concatenate((a, b), axis=0)

print(result)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
import numpy as np

# Define arrays a and b
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

# Concatenate arrays a and b along columns (horizontally)
result = np.concatenate((a, b), axis=1)

print(result)


[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
